plugins:
  - rubocop-performance
  - rubocop-rspec

inherit_mode:
  merge:
    - Exclude

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable

# Stylistic preference for cucumber
Gemspec/DevelopmentDependencies:
  Enabled: false

# Disabled on our repo's to enable polyglot-release
Gemspec/RequireMFA:
  Enabled: false
