name: Release NPM

on:
  push:
    branches: [release/*]

permissions:
  id-token: write
  contents: read

jobs:
  publish-npm:
    name: Publish NPM module
    runs-on: ubuntu-latest
    environment: Release
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: '22'
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
        working-directory: javascript
      - run: npm test
        working-directory: javascript
      - run: npm publish
        working-directory: javascript
